version: '3'
services:
    web:
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - "8000:8000"
        environment:
            NRMM_KEY_ID: ${NRMM_KEY_ID}
            NRMM_SECRET: ${NRMM_SECRET}